### ISSUE TITLE
Mention windows-latest in README example

### ISSUE THREAD

**Issue by vindarel** [melusina-org/make-common-lisp-program#1]
Hello,

The README example could mention windows, as you built a successful workflow for the 3 major platforms in https://github.com/melusina-org/make-common-lisp-program/actions/runs/6415297009/workflow

thanks

**Comment by foretspaisibles** [comment]
Done! Thank you for your interest in this GitHub action. Do you mind describing your use case or if you're experimenting? Or what's refraining you to do so? You're welcome to be liberal in opening issues/discussions! (I'm currently parenting and have little time available to continue writing these GitHub actions but soon it should be easier to do so.)

**Comment by vindarel** [comment]
sure. I know Gitlab CI, but I'd like to build Windows binaries, and building Windows apps there doesn't look as first class citizen as it is on Github. I then want to learn Github Actions and your project seems like a good starting point. I am experimenting. I got a pipeline running, it failed on a linux dependency (readline), I must tweak the project on my side now. It took 13 minutes to install all the Quicklisp dependencies though :/

Happy time parenting!

**Comment by foretspaisibles** [comment]
With GitHub actions we must deal with a rather long feedback loop and it is very hard to test the actions… the system has a few other shortcomings and I am overall not a huge fan of it but let's say I'm a pragmatic user. I am writing these actions with the goal of having simple continuous integration and delivery of Common Lisp programs for every GitHub user, to 1/increases the visibility of the language, 2/increase its legitimacy as a choice in the industry and 3/help CL fellows use to agree on a common toolset. Do you other goals which could benefit from these actions?

You probably already saw a few other actions I am writing that could be interesting for you, they are mentioned in the README. (setup-common-lisp, setup-quicklisp & co) The work is still at an early stage but if you are interested in using it under windows, you're more than welcome to report bugs, ask for features or make any other suggestion.

Have you ever tried https://github.com/40ants/ci/ It's a GitHub Actions generator by @svetlyak40wt which I never had the leisure to test. It looks very interesting though.

If you are interesting in caching to speed up your 13 minutes QuickLisp installation, you can see and example of GitHub Actions Cache here: https://github.com/melusina-org/setup-macports/blob/main/action.yaml — It is fairly easy to use.

**Comment by foretspaisibles** [comment]
> Happy time parenting!

Thanks!
